insert into exercises (slug, movement, name, type, rounds, unilateral) values
  ('nordic_curl',         'nordic_curl',         'Nordic Curls',        'fixed',     null, false),
  ('rest',                'rest',                'Rest',                'plain',     null, false),
  ('zercher_squat',       'zercher_squat',       'Zercher Squats',      'ramp_up',      4, false),
  ('lm_lateral_raise',    'lm_lateral_raise',    'LM Lateral Raises',   'fixed',     null, true),
  ('kb_incline_press',    'kb_incline_press',    'KB Incline Press',    'fixed',     null, true),
  ('overhead_press',      'overhead_press',      'Overhead Press',      'ramp_up',      4, false),
  ('gorilla_row',         'gorilla_row',         'Gorilla Rows',        'fixed',     null, true),
  ('lm_meadows_row',      'lm_meadows_row',      'LM Meadows Rows',     'fixed',     null, true),
  ('ring_face_pull',      'ring_face_pull',      'Ring Face Pulls',     'fixed',     null, false),
  ('chin_up',             'chin_up',             'Chin-ups',            'rep_range', null, false),
  ('goblet_squat',        'goblet_squat',        'Goblet Squat',        'fixed',     null, false),
  ('incline_bench_press', 'incline_bench_press', 'Incline Bench Press', 'fixed',     null, false),
  ('one_leg_kb_rdl',      'one_leg_kb_rdl',      '1-leg KB RDL',        'fixed',     null, true),
  ('sumo_deadlift',       'sumo_deadlift',       'Sumo Deadlifts',      'ramp_up',      4, false),
  ('push_up_on_kbs',      'push_up_on_kbs',      'Push-ups on KBs',     'fixed',     null, false),
  ('cossack_squat',       'cossack_squat',       'Cossack Squats',      'fixed',     null, true),
  ('carry',               'carry',               'Carry!',              'plain',     null, false),
  ('skip',                'skip',                'Skip!',               'plain',     null, false);

-- 'plain' exercises (rest, carry, skip) deliberately have no prescription.
insert into prescriptions (exercise_slug, reps_min, reps_max, weights) values
  ('nordic_curl',          5,  5, '{0}'),
  ('zercher_squat',       10, 10, '{45,50,60,60}'),
  ('lm_lateral_raise',    12, 12, '{2.5}'),
  ('kb_incline_press',    10, 10, '{16}'),
  ('overhead_press',       8,  8, '{35,40,45,40}'),
  ('gorilla_row',         10, 10, '{32}'),
  ('lm_meadows_row',      10, 10, '{22.5}'),
  ('ring_face_pull',      12, 12, '{0}'),
  ('chin_up',              5,  8, '{18.5}'),
  ('goblet_squat',        15, 15, '{24}'),
  ('incline_bench_press', 10, 10, '{45}'),
  ('one_leg_kb_rdl',       8,  8, '{32}'),
  ('sumo_deadlift',        6,  6, '{80,90,110,100}'),
  ('push_up_on_kbs',      20, 20, '{0}'),
  ('cossack_squat',        8,  8, '{16}');

insert into workouts (id, title, day, rounds, position) values
  ('squat_main',     'Squat Main',       'monday',   4, 1),
  ('squat_acc',      'Squat Accessory',  'monday',   6, 2),
  ('upper_main',     'Upper Main',       'tuesday',  4, 3),
  ('upper_acc',      'Upper Accessory',  'tuesday',  4, 4),
  ('full_body',      'Full Body',        'thursday', 4, 5),
  ('hinge_main',     'Hinge Main',       'friday',   4, 6),
  ('hinge_acc',      'Hinge Accessory',  'friday',   3, 7),
  ('loaded_carries', 'Loaded Carries',   null,       5, 8),
  ('jump_rope',      'Jump Rope',        null,       7, 9);

insert into workout_slots (workout_id, position, exercise_slug, side) values
  ('squat_main',     1, 'nordic_curl',         null),
  ('squat_main',     2, 'rest',                null),
  ('squat_main',     3, 'zercher_squat',       null),
  ('squat_acc',      1, 'lm_lateral_raise',    'per_round'),
  ('squat_acc',      2, 'kb_incline_press',    'per_round'),
  ('upper_main',     1, 'overhead_press',      null),
  ('upper_main',     2, 'gorilla_row',         'alternating'),
  ('upper_main',     3, 'rest',                null),
  ('upper_acc',      1, 'lm_meadows_row',      'per_round'),
  ('upper_acc',      2, 'rest',                null),
  ('upper_acc',      3, 'ring_face_pull',      null),
  ('full_body',      1, 'chin_up',             null),
  ('full_body',      2, 'goblet_squat',        null),
  ('full_body',      3, 'incline_bench_press', null),
  ('full_body',      4, 'one_leg_kb_rdl',      'per_round'),
  ('hinge_main',     1, 'sumo_deadlift',       null),
  ('hinge_main',     2, 'push_up_on_kbs',      null),
  ('hinge_main',     3, 'rest',                null),
  ('hinge_acc',      1, 'cossack_squat',       'alternating'),
  ('hinge_acc',      2, 'lm_lateral_raise',    'alternating'),
  ('loaded_carries', 1, 'carry',               null),
  ('jump_rope',      1, 'skip',                null);
